import { T } from './utils.js';

export const LEVELS = [
    // ===== LEVEL 1: Boot Camp =====
    {
        id: 1,
        name: 'Boot Camp',
        subtitle: 'Learn the basics',
        briefing: 'Commander, welcome to boot camp. Build your base, train a small force, and destroy the enemy outpost to the east. This will teach you the fundamentals of base construction and unit command.',
        objectives: ['Build a Power Plant', 'Build a Barracks', 'Train 5 Infantry', 'Destroy the enemy Pillbox'],
        mapSize: { w: 40, h: 30 },
        playerStart: { x: 3, y: 15 },
        enemyStart: { x: 33, y: 15 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 13 },
        ],
        playerUnits: [],
        enemyBuildings: [
            { type: 'pillbox', x: 34, y: 14 },
        ],
        enemyUnits: [
            { type: 'infantry', x: 33, y: 18 },
            { type: 'infantry', x: 34, y: 18 },
        ],
        playerCredits: 3000,
        enemyCredits: 0,
        terrain: [
            { type: 'rect', x: 0, y: 0, w: 40, h: 2, tile: T.WATER },
            { type: 'rect', x: 0, y: 28, w: 40, h: 2, tile: T.WATER },
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 20, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'barracks', 'pillbox'],
        availableUnits: ['infantry'],
        aiDifficulty: 0.2,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 101,
    },
    // ===== LEVEL 2: First Blood =====
    {
        id: 2,
        name: 'First Blood',
        subtitle: 'Your first real battle',
        briefing: 'The enemy has established a small forward base. Build up your forces and destroy it. Remember: Ore Refineries provide the credits you need to fund your war machine.',
        objectives: ['Build an Ore Refinery', 'Build a War Factory', 'Destroy all enemy buildings'],
        mapSize: { w: 45, h: 35 },
        playerStart: { x: 4, y: 17 },
        enemyStart: { x: 38, y: 17 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 15 },
            { type: 'power_plant', x: 7, y: 15 },
        ],
        playerUnits: [
            { type: 'infantry', x: 5, y: 19 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 37, y: 15 },
            { type: 'power_plant', x: 41, y: 15 },
            { type: 'barracks', x: 41, y: 18 },
            { type: 'pillbox', x: 36, y: 18 },
        ],
        enemyUnits: [
            { type: 'infantry', x: 39, y: 20 },
            { type: 'infantry', x: 40, y: 20 },
            { type: 'infantry', x: 39, y: 21 },
        ],
        playerCredits: 5000,
        enemyCredits: 3000,
        terrain: [
            { type: 'scatter', count: 60, tile: T.ORE },
            { type: 'rect', x: 20, y: 10, w: 1, h: 15, tile: T.ROCK },
            { type: 'scatter', count: 30, tile: T.ROCK },
            { type: 'scatter', count: 50, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'pillbox'],
        availableUnits: ['infantry', 'light_tank', 'harvester'],
        aiDifficulty: 0.3,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 202,
    },
    // ===== LEVEL 3: Hold the Line =====
    {
        id: 3,
        name: 'Hold the Line',
        subtitle: 'Survive the assault',
        briefing: 'The enemy will attack in waves. Build defenses and hold your position for 8 minutes. If your Construction Yard is destroyed, the mission fails.',
        objectives: ['Survive for 8 minutes', 'Protect your Construction Yard'],
        mapSize: { w: 40, h: 30 },
        playerStart: { x: 20, y: 25 },
        enemyStart: { x: 20, y: 3 },
        playerBuildings: [
            { type: 'construction_yard', x: 18, y: 23 },
            { type: 'power_plant', x: 22, y: 23 },
            { type: 'barracks', x: 22, y: 26 },
            { type: 'ore_refinery', x: 15, y: 23 },
        ],
        playerUnits: [
            { type: 'infantry', x: 19, y: 22 },
            { type: 'infantry', x: 21, y: 22 },
            { type: 'light_tank', x: 17, y: 22 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 18, y: 2 },
            { type: 'barracks', x: 22, y: 2 },
            { type: 'power_plant', x: 22, y: 5 },
        ],
        enemyUnits: [],
        playerCredits: 4000,
        enemyCredits: 8000,
        terrain: [
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'rect', x: 0, y: 0, w: 40, h: 1, tile: T.WATER },
            { type: 'scatter', count: 25, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'light_tank', 'heavy_tank', 'harvester'],
        aiDifficulty: 0.4,
        victoryCondition: 'survive_time',
        surviveTime: 480,
        timeLimit: 0,
        seed: 303,
    },
    // ===== LEVEL 4: River Crossing =====
    {
        id: 4,
        name: 'River Crossing',
        subtitle: 'Bridge the gap',
        briefing: 'A river divides the battlefield. Two bridges provide crossing points. The enemy has fortified the far bank. Capture a bridgehead and destroy their base.',
        objectives: ['Cross the river', 'Destroy all enemy buildings'],
        mapSize: { w: 50, h: 35 },
        playerStart: { x: 5, y: 17 },
        enemyStart: { x: 42, y: 17 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 15 },
            { type: 'power_plant', x: 7, y: 15 },
            { type: 'ore_refinery', x: 3, y: 19 },
        ],
        playerUnits: [
            { type: 'light_tank', x: 5, y: 18 },
            { type: 'infantry', x: 6, y: 18 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 42, y: 15 },
            { type: 'power_plant', x: 46, y: 15 },
            { type: 'barracks', x: 46, y: 18 },
            { type: 'turret', x: 38, y: 15 },
            { type: 'turret', x: 38, y: 19 },
            { type: 'pillbox', x: 39, y: 17 },
        ],
        enemyUnits: [
            { type: 'infantry', x: 38, y: 16 },
            { type: 'infantry', x: 39, y: 14 },
            { type: 'light_tank', x: 37, y: 18 },
        ],
        playerCredits: 5000,
        enemyCredits: 5000,
        terrain: [
            { type: 'rect', x: 0, y: 16, w: 50, h: 3, tile: T.WATER },
            { type: 'rect', x: 14, y: 16, w: 2, h: 3, tile: T.BRIDGE },
            { type: 'rect', x: 34, y: 16, w: 2, h: 3, tile: T.BRIDGE },
            { type: 'scatter', count: 50, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'light_tank', 'heavy_tank', 'harvester'],
        aiDifficulty: 0.45,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 404,
    },
    // ===== LEVEL 5: Oil Spill =====
    {
        id: 5,
        name: 'Oil Spill',
        subtitle: 'Control the resources',
        briefing: 'Massive ore deposits have been discovered in the center of the map. Both sides are racing to claim them. Control the center and use the economic advantage to crush the enemy.',
        objectives: ['Establish control of central ore fields', 'Destroy enemy base'],
        mapSize: { w: 50, h: 40 },
        playerStart: { x: 5, y: 20 },
        enemyStart: { x: 44, y: 20 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 18 },
            { type: 'power_plant', x: 7, y: 18 },
            { type: 'ore_refinery', x: 3, y: 22 },
            { type: 'barracks', x: 7, y: 21 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 22 },
            { type: 'infantry', x: 5, y: 23 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 42, y: 18 },
            { type: 'power_plant', x: 46, y: 18 },
            { type: 'ore_refinery', x: 42, y: 22 },
            { type: 'barracks', x: 46, y: 21 },
        ],
        enemyUnits: [
            { type: 'harvester', x: 45, y: 22 },
            { type: 'infantry', x: 44, y: 23 },
        ],
        playerCredits: 4000,
        enemyCredits: 4000,
        terrain: [
            { type: 'circle', cx: 25, cy: 20, r: 8, tile: T.ORE },
            { type: 'circle', cx: 25, cy: 20, r: 3, tile: T.ORE },
            { type: 'scatter', count: 20, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.FOREST },
            { type: 'scatter', count: 20, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'harvester'],
        aiDifficulty: 0.5,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 505,
    },
    // ===== LEVEL 6: Fortress =====
    {
        id: 6,
        name: 'Fortress',
        subtitle: 'Break through defenses',
        briefing: 'The enemy has constructed a heavily fortified base with turrets and pillboxes. You\'ll need overwhelming force to crack their defenses. Use artillery to soften their perimeter.',
        objectives: ['Destroy the enemy fortress', 'Eliminate all enemy structures'],
        mapSize: { w: 50, h: 35 },
        playerStart: { x: 5, y: 17 },
        enemyStart: { x: 40, y: 17 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 15 },
            { type: 'power_plant', x: 7, y: 15 },
            { type: 'ore_refinery', x: 3, y: 19 },
            { type: 'barracks', x: 7, y: 18 },
            { type: 'war_factory', x: 3, y: 22 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 22 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 40, y: 14 },
            { type: 'power_plant', x: 44, y: 14 },
            { type: 'advanced_power', x: 44, y: 17 },
            { type: 'barracks', x: 40, y: 18 },
            { type: 'war_factory', x: 40, y: 21 },
            { type: 'turret', x: 36, y: 13 },
            { type: 'turret', x: 36, y: 17 },
            { type: 'turret', x: 36, y: 21 },
            { type: 'pillbox', x: 37, y: 15 },
            { type: 'pillbox', x: 37, y: 19 },
            { type: 'pillbox', x: 38, y: 13 },
            { type: 'pillbox', x: 38, y: 21 },
        ],
        enemyUnits: [
            { type: 'light_tank', x: 39, y: 20 },
            { type: 'infantry', x: 38, y: 16 },
            { type: 'infantry', x: 39, y: 14 },
            { type: 'infantry', x: 39, y: 22 },
            { type: 'rocket_soldier', x: 38, y: 18 },
        ],
        playerCredits: 6000,
        enemyCredits: 4000,
        terrain: [
            { type: 'scatter', count: 50, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.FOREST },
            { type: 'scatter', count: 25, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.55,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 606,
    },
    // ===== LEVEL 7: Behind Enemy Lines =====
    {
        id: 7,
        name: 'Behind Enemy Lines',
        subtitle: 'Infiltrate and destroy',
        briefing: 'You have a small strike team behind enemy lines. No base construction available. Use your forces wisely to sabotage the enemy power grid and destroy their HQ.',
        objectives: ['Destroy enemy Power Plants', 'Destroy enemy Construction Yard'],
        mapSize: { w: 45, h: 35 },
        playerStart: { x: 35, y: 28 },
        enemyStart: { x: 20, y: 10 },
        playerBuildings: [],
        playerUnits: [
            { type: 'heavy_tank', x: 36, y: 28 },
            { type: 'heavy_tank', x: 37, y: 28 },
            { type: 'rocket_soldier', x: 36, y: 29 },
            { type: 'rocket_soldier', x: 37, y: 29 },
            { type: 'infantry', x: 36, y: 30 },
            { type: 'infantry', x: 37, y: 30 },
            { type: 'engineer', x: 36, y: 27 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 18, y: 8 },
            { type: 'power_plant', x: 22, y: 8 },
            { type: 'power_plant', x: 22, y: 11 },
            { type: 'advanced_power', x: 25, y: 8 },
            { type: 'barracks', x: 18, y: 12 },
            { type: 'war_factory', x: 25, y: 11 },
            { type: 'ore_refinery', x: 18, y: 15 },
        ],
        enemyUnits: [
            { type: 'light_tank', x: 20, y: 15 },
            { type: 'infantry', x: 22, y: 14 },
            { type: 'infantry', x: 23, y: 14 },
            { type: 'infantry', x: 20, y: 13 },
            { type: 'rocket_soldier', x: 24, y: 13 },
            { type: 'harvester', x: 19, y: 17 },
        ],
        playerCredits: 0,
        enemyCredits: 6000,
        terrain: [
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 50, tile: T.FOREST },
            { type: 'scatter', count: 20, tile: T.ROCK },
        ],
        availableTech: [],
        availableUnits: [],
        aiDifficulty: 0.5,
        victoryCondition: 'destroy_building_type',
        destroyTarget: 'construction_yard',
        noBase: true,
        timeLimit: 600,
        seed: 707,
    },
    // ===== LEVEL 8: Coastal Assault =====
    {
        id: 8,
        name: 'Coastal Assault',
        subtitle: 'Attack from the shore',
        briefing: 'The enemy has built their base along the coast. Approach from the south, using the natural terrain as cover. Long-range units will be essential to breach their shoreline defenses.',
        objectives: ['Destroy the coastal base'],
        mapSize: { w: 55, h: 40 },
        playerStart: { x: 5, y: 35 },
        enemyStart: { x: 42, y: 12 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 33 },
            { type: 'power_plant', x: 7, y: 33 },
            { type: 'ore_refinery', x: 3, y: 36 },
            { type: 'barracks', x: 7, y: 36 },
            { type: 'war_factory', x: 3, y: 30 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 36 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 42, y: 10 },
            { type: 'power_plant', x: 46, y: 10 },
            { type: 'barracks', x: 46, y: 13 },
            { type: 'turret', x: 40, y: 12 },
            { type: 'turret', x: 40, y: 15 },
            { type: 'turret', x: 38, y: 13 },
            { type: 'pillbox', x: 41, y: 16 },
            { type: 'pillbox', x: 39, y: 10 },
        ],
        enemyUnits: [
            { type: 'heavy_tank', x: 42, y: 15 },
            { type: 'light_tank', x: 41, y: 14 },
            { type: 'infantry', x: 40, y: 11 },
            { type: 'rocket_soldier', x: 43, y: 16 },
        ],
        playerCredits: 6000,
        enemyCredits: 5000,
        terrain: [
            { type: 'rect', x: 0, y: 0, w: 55, h: 5, tile: T.WATER },
            { type: 'rect', x: 35, y: 0, w: 20, h: 25, tile: T.SHALLOW_WATER },
            { type: 'rect', x: 37, y: 5, w: 16, h: 20, tile: T.SAND },
            { type: 'scatter', count: 60, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox', 'service_depot'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.6,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 808,
    },
    // ===== LEVEL 9: Race for Resources =====
    {
        id: 9,
        name: 'Race for Resources',
        subtitle: 'Economic warfare',
        briefing: 'Both sides start with minimal forces. Rich ore fields dot the map. The side that controls the economy controls the war. Build fast and expand aggressively.',
        objectives: ['Outproduce and destroy the enemy'],
        mapSize: { w: 55, h: 40 },
        playerStart: { x: 5, y: 20 },
        enemyStart: { x: 49, y: 20 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 18 },
        ],
        playerUnits: [],
        enemyBuildings: [
            { type: 'construction_yard', x: 47, y: 18 },
        ],
        enemyUnits: [],
        playerCredits: 2000,
        enemyCredits: 2000,
        terrain: [
            { type: 'circle', cx: 15, cy: 10, r: 4, tile: T.ORE },
            { type: 'circle', cx: 40, cy: 10, r: 4, tile: T.ORE },
            { type: 'circle', cx: 27, cy: 20, r: 5, tile: T.ORE },
            { type: 'circle', cx: 15, cy: 30, r: 4, tile: T.ORE },
            { type: 'circle', cx: 40, cy: 30, r: 4, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.FOREST },
            { type: 'scatter', count: 15, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'harvester'],
        aiDifficulty: 0.55,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 909,
    },
    // ===== LEVEL 10: The Gauntlet =====
    {
        id: 10,
        name: 'The Gauntlet',
        subtitle: 'Survive the onslaught',
        briefing: 'Waves of increasingly powerful enemy forces will attack from the north. You must survive 10 minutes. The enemy has unlimited resources — this is a pure test of your defensive capabilities.',
        objectives: ['Survive 10 minutes of enemy waves', 'Protect your base'],
        mapSize: { w: 45, h: 40 },
        playerStart: { x: 22, y: 33 },
        enemyStart: { x: 22, y: 3 },
        playerBuildings: [
            { type: 'construction_yard', x: 20, y: 31 },
            { type: 'power_plant', x: 24, y: 31 },
            { type: 'advanced_power', x: 20, y: 28 },
            { type: 'ore_refinery', x: 24, y: 34 },
            { type: 'barracks', x: 17, y: 34 },
            { type: 'war_factory', x: 17, y: 31 },
        ],
        playerUnits: [
            { type: 'harvester', x: 27, y: 34 },
            { type: 'infantry', x: 22, y: 29 },
            { type: 'light_tank', x: 20, y: 29 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 20, y: 2 },
            { type: 'barracks', x: 24, y: 2 },
            { type: 'war_factory', x: 24, y: 5 },
        ],
        enemyUnits: [],
        playerCredits: 5000,
        enemyCredits: 15000,
        terrain: [
            { type: 'rect', x: 0, y: 0, w: 45, h: 2, tile: T.WATER },
            { type: 'scatter', count: 45, tile: T.ORE },
            { type: 'scatter', count: 25, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox', 'aa_gun', 'service_depot'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.7,
        victoryCondition: 'survive_time',
        surviveTime: 600,
        timeLimit: 0,
        seed: 1010,
    },
    // ===== LEVEL 11: Tech War =====
    {
        id: 11,
        name: 'Tech War',
        subtitle: 'Advanced warfare',
        briefing: 'Both sides have access to advanced technology. Build Tech Centers and field advanced units. The enemy is particularly fond of heavy armor — make sure you have rocket soldiers ready.',
        objectives: ['Build a Tech Center', 'Destroy the enemy base'],
        mapSize: { w: 55, h: 40 },
        playerStart: { x: 5, y: 20 },
        enemyStart: { x: 49, y: 20 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 18 },
            { type: 'power_plant', x: 7, y: 18 },
            { type: 'advanced_power', x: 7, y: 21 },
            { type: 'ore_refinery', x: 3, y: 22 },
            { type: 'barracks', x: 3, y: 25 },
            { type: 'war_factory', x: 7, y: 24 },
            { type: 'radar_dome', x: 11, y: 18 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 22 },
            { type: 'heavy_tank', x: 10, y: 26 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 47, y: 18 },
            { type: 'power_plant', x: 51, y: 18 },
            { type: 'advanced_power', x: 51, y: 21 },
            { type: 'ore_refinery', x: 47, y: 22 },
            { type: 'barracks', x: 47, y: 25 },
            { type: 'war_factory', x: 51, y: 24 },
            { type: 'radar_dome', x: 51, y: 27 },
            { type: 'tech_center', x: 55, y: 18 },
            { type: 'turret', x: 45, y: 20 },
            { type: 'turret', x: 45, y: 23 },
        ],
        enemyUnits: [
            { type: 'heavy_tank', x: 48, y: 26 },
            { type: 'heavy_tank', x: 49, y: 26 },
            { type: 'harvester', x: 50, y: 22 },
        ],
        playerCredits: 6000,
        enemyCredits: 6000,
        terrain: [
            { type: 'scatter', count: 60, tile: T.ORE },
            { type: 'scatter', count: 35, tile: T.FOREST },
            { type: 'scatter', count: 25, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'radar_dome', 'tech_center', 'turret', 'pillbox', 'aa_gun'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'engineer', 'light_tank', 'heavy_tank', 'artillery', 'harvester', 'apc'],
        aiDifficulty: 0.65,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1111,
    },
    // ===== LEVEL 12: Divide and Conquer =====
    {
        id: 12,
        name: 'Divide and Conquer',
        subtitle: 'Two fronts, one war',
        briefing: 'The enemy has established two bases — one to the northwest, one to the southeast. You must destroy both. Choose your approach carefully: hit one base at a time, or split your forces.',
        objectives: ['Destroy the northwest enemy base', 'Destroy the southeast enemy base'],
        mapSize: { w: 60, h: 45 },
        playerStart: { x: 30, y: 22 },
        enemyStart: { x: 10, y: 10 },
        playerBuildings: [
            { type: 'construction_yard', x: 28, y: 20 },
            { type: 'power_plant', x: 32, y: 20 },
            { type: 'ore_refinery', x: 28, y: 24 },
            { type: 'barracks', x: 32, y: 23 },
            { type: 'war_factory', x: 28, y: 27 },
        ],
        playerUnits: [
            { type: 'harvester', x: 31, y: 24 },
            { type: 'light_tank', x: 30, y: 28 },
        ],
        enemyBuildings: [
            // Base 1 - NW
            { type: 'construction_yard', x: 8, y: 8 },
            { type: 'power_plant', x: 12, y: 8 },
            { type: 'barracks', x: 8, y: 12 },
            { type: 'turret', x: 7, y: 10 },
            { type: 'turret', x: 14, y: 10 },
            { type: 'pillbox', x: 10, y: 7 },
            // Base 2 - SE
            { type: 'construction_yard', x: 48, y: 34 },
            { type: 'power_plant', x: 52, y: 34 },
            { type: 'barracks', x: 48, y: 38 },
            { type: 'turret', x: 47, y: 36 },
            { type: 'turret', x: 54, y: 36 },
            { type: 'pillbox', x: 50, y: 33 },
        ],
        enemyUnits: [
            { type: 'light_tank', x: 10, y: 13 },
            { type: 'infantry', x: 11, y: 9 },
            { type: 'infantry', x: 13, y: 11 },
            { type: 'light_tank', x: 50, y: 39 },
            { type: 'infantry', x: 51, y: 35 },
            { type: 'infantry', x: 53, y: 37 },
        ],
        playerCredits: 7000,
        enemyCredits: 8000,
        terrain: [
            { type: 'circle', cx: 10, cy: 10, r: 4, tile: T.ORE },
            { type: 'circle', cx: 50, cy: 36, r: 4, tile: T.ORE },
            { type: 'circle', cx: 30, cy: 22, r: 3, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 50, tile: T.FOREST },
            { type: 'scatter', count: 30, tile: T.ROCK },
            { type: 'scatter', count: 10, tile: T.WATER },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.65,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1212,
    },
    // ===== LEVEL 13: Supply Lines =====
    {
        id: 13,
        name: 'Supply Lines',
        subtitle: 'Protect your harvesters',
        briefing: 'The enemy will send raiding parties to attack your harvesters. Protect your supply lines while building up enough forces to mount a counter-offensive. Your economy is the key to victory.',
        objectives: ['Maintain a steady income', 'Destroy the enemy base'],
        mapSize: { w: 50, h: 38 },
        playerStart: { x: 5, y: 19 },
        enemyStart: { x: 44, y: 8 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 17 },
            { type: 'power_plant', x: 7, y: 17 },
            { type: 'ore_refinery', x: 3, y: 20 },
            { type: 'barracks', x: 7, y: 20 },
            { type: 'war_factory', x: 3, y: 23 },
            { type: 'turret', x: 7, y: 23 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 20 },
            { type: 'infantry', x: 8, y: 22 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 42, y: 6 },
            { type: 'power_plant', x: 46, y: 6 },
            { type: 'barracks', x: 46, y: 9 },
            { type: 'war_factory', x: 42, y: 9 },
        ],
        enemyUnits: [
            { type: 'light_tank', x: 40, y: 12 },
            { type: 'light_tank', x: 42, y: 12 },
        ],
        playerCredits: 5000,
        enemyCredits: 8000,
        terrain: [
            { type: 'circle', cx: 20, cy: 10, r: 5, tile: T.ORE },
            { type: 'circle', cx: 15, cy: 28, r: 4, tile: T.ORE },
            { type: 'circle', cx: 35, cy: 25, r: 4, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.7,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1313,
    },
    // ===== LEVEL 14: Blitzkrieg =====
    {
        id: 14,
        name: 'Blitzkrieg',
        subtitle: 'Speed is everything',
        briefing: 'You have a massive starting force and 5 minutes to destroy the enemy base before their reinforcements arrive. Attack fast and attack hard — hesitation means defeat!',
        objectives: ['Destroy the enemy base within 5 minutes'],
        mapSize: { w: 50, h: 35 },
        playerStart: { x: 5, y: 17 },
        enemyStart: { x: 42, y: 17 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 15 },
            { type: 'power_plant', x: 7, y: 15 },
            { type: 'ore_refinery', x: 3, y: 18 },
            { type: 'barracks', x: 7, y: 18 },
            { type: 'war_factory', x: 3, y: 21 },
        ],
        playerUnits: [
            { type: 'heavy_tank', x: 10, y: 20 },
            { type: 'heavy_tank', x: 11, y: 20 },
            { type: 'heavy_tank', x: 12, y: 20 },
            { type: 'light_tank', x: 10, y: 22 },
            { type: 'light_tank', x: 11, y: 22 },
            { type: 'light_tank', x: 12, y: 22 },
            { type: 'rocket_soldier', x: 10, y: 18 },
            { type: 'rocket_soldier', x: 11, y: 18 },
            { type: 'infantry', x: 12, y: 18 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 42, y: 15 },
            { type: 'power_plant', x: 46, y: 15 },
            { type: 'barracks', x: 46, y: 18 },
            { type: 'turret', x: 40, y: 16 },
            { type: 'turret', x: 40, y: 19 },
            { type: 'pillbox', x: 41, y: 17 },
        ],
        enemyUnits: [
            { type: 'infantry', x: 42, y: 20 },
            { type: 'light_tank', x: 41, y: 21 },
        ],
        playerCredits: 4000,
        enemyCredits: 3000,
        terrain: [
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.FOREST },
            { type: 'scatter', count: 15, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'ore_refinery', 'barracks', 'war_factory'],
        availableUnits: ['infantry', 'rocket_soldier', 'light_tank', 'heavy_tank', 'harvester'],
        aiDifficulty: 0.6,
        victoryCondition: 'destroy_all',
        timeLimit: 300,
        seed: 1414,
    },
    // ===== LEVEL 15: Diplomatic Incident =====
    {
        id: 15,
        name: 'Diplomatic Incident',
        subtitle: 'Multi-directional warfare',
        briefing: 'The enemy will attack from multiple directions. They have set up forward bases to the north and east. You must defend your HQ while taking out their forward positions.',
        objectives: ['Destroy the northern forward base', 'Destroy the eastern forward base'],
        mapSize: { w: 55, h: 45 },
        playerStart: { x: 27, y: 35 },
        enemyStart: { x: 27, y: 8 },
        playerBuildings: [
            { type: 'construction_yard', x: 25, y: 33 },
            { type: 'power_plant', x: 29, y: 33 },
            { type: 'advanced_power', x: 25, y: 30 },
            { type: 'ore_refinery', x: 29, y: 36 },
            { type: 'barracks', x: 25, y: 37 },
            { type: 'war_factory', x: 29, y: 39 },
            { type: 'turret', x: 25, y: 39 },
            { type: 'turret', x: 29, y: 30 },
        ],
        playerUnits: [
            { type: 'harvester', x: 32, y: 36 },
            { type: 'light_tank', x: 27, y: 30 },
        ],
        enemyBuildings: [
            // Main base - N
            { type: 'construction_yard', x: 25, y: 6 },
            { type: 'power_plant', x: 29, y: 6 },
            { type: 'barracks', x: 25, y: 9 },
            { type: 'war_factory', x: 29, y: 9 },
            // Forward base - E
            { type: 'barracks', x: 48, y: 25 },
            { type: 'turret', x: 46, y: 27 },
            { type: 'pillbox', x: 47, y: 23 },
            { type: 'turret', x: 46, y: 22 },
        ],
        enemyUnits: [
            { type: 'light_tank', x: 35, y: 20 },
            { type: 'heavy_tank', x: 30, y: 15 },
            { type: 'infantry', x: 40, y: 25 },
            { type: 'rocket_soldier', x: 45, y: 26 },
        ],
        playerCredits: 6000,
        enemyCredits: 10000,
        terrain: [
            { type: 'scatter', count: 55, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.FOREST },
            { type: 'scatter', count: 20, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'radar_dome', 'tech_center', 'turret', 'pillbox', 'aa_gun'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'engineer', 'light_tank', 'heavy_tank', 'artillery', 'harvester', 'apc'],
        aiDifficulty: 0.7,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1515,
    },
    // ===== LEVEL 16: Mountain Pass =====
    {
        id: 16,
        name: 'Mountain Pass',
        subtitle: 'Use the terrain',
        briefing: 'A mountain range divides the map with only a few passes. The enemy has fortified the key chokepoints. Use artillery to clear the way and push through the mountain passes.',
        objectives: ['Break through the mountain defenses', 'Destroy the enemy base'],
        mapSize: { w: 55, h: 40 },
        playerStart: { x: 5, y: 20 },
        enemyStart: { x: 48, y: 20 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 18 },
            { type: 'power_plant', x: 7, y: 18 },
            { type: 'ore_refinery', x: 3, y: 21 },
            { type: 'barracks', x: 7, y: 21 },
            { type: 'war_factory', x: 3, y: 24 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 21 },
            { type: 'light_tank', x: 10, y: 25 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 46, y: 18 },
            { type: 'power_plant', x: 50, y: 18 },
            { type: 'ore_refinery', x: 46, y: 21 },
            { type: 'barracks', x: 50, y: 21 },
            { type: 'turret', x: 35, y: 18 },
            { type: 'turret', x: 35, y: 22 },
            { type: 'pillbox', x: 36, y: 20 },
        ],
        enemyUnits: [
            { type: 'heavy_tank', x: 37, y: 20 },
            { type: 'infantry', x: 36, y: 19 },
            { type: 'infantry', x: 36, y: 21 },
        ],
        playerCredits: 6000,
        enemyCredits: 5000,
        terrain: [
            // Mountain range across middle
            { type: 'rect', x: 28, y: 0, w: 3, h: 12, tile: T.ROCK },
            { type: 'rect', x: 28, y: 14, w: 3, h: 3, tile: T.ROCK },
            { type: 'rect', x: 28, y: 20, w: 3, h: 1, tile: T.ROCK },
            { type: 'rect', x: 28, y: 23, w: 3, h: 17, tile: T.ROCK },
            // Pass gaps at y=12-13 and y=21-22
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 25, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.7,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1616,
    },
    // ===== LEVEL 17: Total War =====
    {
        id: 17,
        name: 'Total War',
        subtitle: 'Full-scale conflict',
        briefing: 'This is total war. Both sides have full access to all technology. Build the ultimate army and crush the enemy completely. No mercy, no prisoners.',
        objectives: ['Annihilate the enemy'],
        mapSize: { w: 65, h: 50 },
        playerStart: { x: 8, y: 25 },
        enemyStart: { x: 56, y: 25 },
        playerBuildings: [
            { type: 'construction_yard', x: 5, y: 22 },
            { type: 'power_plant', x: 9, y: 22 },
            { type: 'advanced_power', x: 9, y: 25 },
            { type: 'ore_refinery', x: 5, y: 26 },
            { type: 'barracks', x: 5, y: 29 },
            { type: 'war_factory', x: 9, y: 28 },
            { type: 'radar_dome', x: 13, y: 22 },
            { type: 'tech_center', x: 13, y: 25 },
            { type: 'turret', x: 4, y: 25 },
            { type: 'turret', x: 4, y: 28 },
        ],
        playerUnits: [
            { type: 'harvester', x: 8, y: 26 },
            { type: 'heavy_tank', x: 12, y: 30 },
            { type: 'infantry', x: 14, y: 22 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 54, y: 22 },
            { type: 'power_plant', x: 58, y: 22 },
            { type: 'advanced_power', x: 58, y: 25 },
            { type: 'ore_refinery', x: 54, y: 26 },
            { type: 'barracks', x: 54, y: 29 },
            { type: 'war_factory', x: 58, y: 28 },
            { type: 'radar_dome', x: 54, y: 32 },
            { type: 'tech_center', x: 58, y: 31 },
            { type: 'turret', x: 53, y: 25 },
            { type: 'turret', x: 53, y: 28 },
            { type: 'aa_gun', x: 56, y: 20 },
        ],
        enemyUnits: [
            { type: 'harvester', x: 57, y: 26 },
            { type: 'heavy_tank', x: 56, y: 30 },
            { type: 'artillery', x: 58, y: 20 },
            { type: 'infantry', x: 55, y: 31 },
        ],
        playerCredits: 8000,
        enemyCredits: 8000,
        terrain: [
            { type: 'circle', cx: 20, cy: 15, r: 4, tile: T.ORE },
            { type: 'circle', cx: 45, cy: 15, r: 4, tile: T.ORE },
            { type: 'circle', cx: 32, cy: 25, r: 5, tile: T.ORE },
            { type: 'circle', cx: 20, cy: 38, r: 4, tile: T.ORE },
            { type: 'circle', cx: 45, cy: 38, r: 4, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.ORE },
            { type: 'scatter', count: 50, tile: T.FOREST },
            { type: 'scatter', count: 30, tile: T.ROCK },
            { type: 'scatter', count: 5, tile: T.WATER },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'radar_dome', 'tech_center', 'turret', 'pillbox', 'aa_gun', 'service_depot'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'engineer', 'spy', 'light_tank', 'heavy_tank', 'artillery', 'harvester', 'apc', 'helicopter', 'mammoth_tank'],
        aiDifficulty: 0.8,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1717,
    },
    // ===== LEVEL 18: Last Stand =====
    {
        id: 18,
        name: 'Last Stand',
        subtitle: 'Defend at all costs',
        briefing: 'Your main base has been destroyed! All you have left is a small forward base with limited resources. The enemy thinks they\'ve won — prove them wrong. Survive the initial assault, rebuild, and counter-attack!',
        objectives: ['Survive the initial assault', 'Rebuild your forces', 'Destroy the enemy base'],
        mapSize: { w: 55, h: 40 },
        playerStart: { x: 15, y: 30 },
        enemyStart: { x: 40, y: 10 },
        playerBuildings: [
            { type: 'construction_yard', x: 13, y: 28 },
            { type: 'power_plant', x: 17, y: 28 },
            { type: 'barracks', x: 13, y: 31 },
        ],
        playerUnits: [
            { type: 'infantry', x: 15, y: 27 },
            { type: 'infantry', x: 16, y: 27 },
            { type: 'rocket_soldier', x: 15, y: 26 },
            { type: 'light_tank', x: 18, y: 30 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 38, y: 8 },
            { type: 'power_plant', x: 42, y: 8 },
            { type: 'advanced_power', x: 42, y: 11 },
            { type: 'ore_refinery', x: 38, y: 12 },
            { type: 'barracks', x: 38, y: 15 },
            { type: 'war_factory', x: 42, y: 14 },
            { type: 'tech_center', x: 46, y: 8 },
            { type: 'turret', x: 36, y: 10 },
            { type: 'turret', x: 36, y: 14 },
        ],
        enemyUnits: [
            { type: 'heavy_tank', x: 30, y: 20 },
            { type: 'heavy_tank', x: 32, y: 22 },
            { type: 'light_tank', x: 28, y: 24 },
            { type: 'light_tank', x: 34, y: 18 },
            { type: 'infantry', x: 25, y: 22 },
            { type: 'infantry', x: 26, y: 23 },
            { type: 'artillery', x: 30, y: 18 },
        ],
        playerCredits: 1500,
        enemyCredits: 12000,
        terrain: [
            { type: 'circle', cx: 15, cy: 35, r: 3, tile: T.ORE },
            { type: 'circle', cx: 25, cy: 10, r: 4, tile: T.ORE },
            { type: 'circle', cx: 40, cy: 30, r: 4, tile: T.ORE },
            { type: 'scatter', count: 30, tile: T.ORE },
            { type: 'scatter', count: 40, tile: T.FOREST },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'turret', 'pillbox'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'light_tank', 'heavy_tank', 'artillery', 'harvester'],
        aiDifficulty: 0.75,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1818,
    },
    // ===== LEVEL 19: The Iron Curtain =====
    {
        id: 19,
        name: 'The Iron Curtain',
        subtitle: 'Crack the fortress',
        briefing: 'The enemy has constructed the most heavily defended base we\'ve ever seen. Multiple layers of turrets, AA guns, and heavy armor guard their headquarters. Only a massive, well-coordinated assault will succeed.',
        objectives: ['Destroy the Iron Curtain HQ', 'Survive the counter-attack'],
        mapSize: { w: 60, h: 45 },
        playerStart: { x: 5, y: 22 },
        enemyStart: { x: 50, y: 22 },
        playerBuildings: [
            { type: 'construction_yard', x: 3, y: 20 },
            { type: 'power_plant', x: 7, y: 20 },
            { type: 'advanced_power', x: 7, y: 23 },
            { type: 'ore_refinery', x: 3, y: 24 },
            { type: 'ore_refinery', x: 3, y: 27 },
            { type: 'barracks', x: 7, y: 26 },
            { type: 'war_factory', x: 3, y: 30 },
            { type: 'radar_dome', x: 7, y: 29 },
            { type: 'tech_center', x: 11, y: 20 },
            { type: 'service_depot', x: 11, y: 23 },
        ],
        playerUnits: [
            { type: 'harvester', x: 6, y: 24 },
            { type: 'harvester', x: 6, y: 27 },
            { type: 'heavy_tank', x: 12, y: 30 },
            { type: 'artillery', x: 13, y: 30 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 50, y: 20 },
            { type: 'power_plant', x: 54, y: 20 },
            { type: 'advanced_power', x: 54, y: 23 },
            { type: 'advanced_power', x: 54, y: 26 },
            { type: 'ore_refinery', x: 50, y: 24 },
            { type: 'barracks', x: 50, y: 27 },
            { type: 'war_factory', x: 54, y: 29 },
            { type: 'tech_center', x: 50, y: 30 },
            // Defense ring
            { type: 'turret', x: 46, y: 20 },
            { type: 'turret', x: 46, y: 23 },
            { type: 'turret', x: 46, y: 26 },
            { type: 'turret', x: 46, y: 29 },
            { type: 'pillbox', x: 47, y: 21 },
            { type: 'pillbox', x: 47, y: 25 },
            { type: 'pillbox', x: 47, y: 28 },
            { type: 'aa_gun', x: 48, y: 22 },
            { type: 'aa_gun', x: 48, y: 27 },
        ],
        enemyUnits: [
            { type: 'mammoth_tank', x: 48, y: 31 },
            { type: 'heavy_tank', x: 49, y: 31 },
            { type: 'heavy_tank', x: 48, y: 32 },
            { type: 'artillery', x: 45, y: 22 },
            { type: 'harvester', x: 53, y: 24 },
        ],
        playerCredits: 10000,
        enemyCredits: 8000,
        terrain: [
            { type: 'scatter', count: 60, tile: T.ORE },
            { type: 'scatter', count: 35, tile: T.FOREST },
            { type: 'scatter', count: 25, tile: T.ROCK },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'radar_dome', 'tech_center', 'turret', 'pillbox', 'aa_gun', 'service_depot'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'engineer', 'spy', 'light_tank', 'heavy_tank', 'artillery', 'harvester', 'apc', 'helicopter', 'mammoth_tank'],
        aiDifficulty: 0.85,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 1919,
    },
    // ===== LEVEL 20: Final Victory =====
    {
        id: 20,
        name: 'Final Victory',
        subtitle: 'The ultimate battle',
        briefing: 'This is it, Commander. The final battle. The enemy has thrown everything they have at this one base. Full technology, massive defenses, and endless resources. You must marshal all your skill and experience to achieve total victory. The fate of the free world rests on your shoulders. Good luck!',
        objectives: ['Destroy the enemy headquarters', 'Achieve final victory'],
        mapSize: { w: 70, h: 55 },
        playerStart: { x: 8, y: 27 },
        enemyStart: { x: 60, y: 27 },
        playerBuildings: [
            { type: 'construction_yard', x: 5, y: 24 },
            { type: 'power_plant', x: 9, y: 24 },
            { type: 'advanced_power', x: 9, y: 27 },
            { type: 'ore_refinery', x: 5, y: 28 },
            { type: 'ore_refinery', x: 5, y: 31 },
            { type: 'barracks', x: 9, y: 30 },
            { type: 'war_factory', x: 5, y: 34 },
            { type: 'radar_dome', x: 9, y: 33 },
            { type: 'tech_center', x: 13, y: 24 },
            { type: 'service_depot', x: 13, y: 27 },
            { type: 'turret', x: 4, y: 27 },
            { type: 'turret', x: 4, y: 30 },
            { type: 'aa_gun', x: 4, y: 33 },
        ],
        playerUnits: [
            { type: 'harvester', x: 8, y: 28 },
            { type: 'harvester', x: 8, y: 31 },
            { type: 'mammoth_tank', x: 14, y: 34 },
            { type: 'heavy_tank', x: 15, y: 34 },
            { type: 'helicopter', x: 14, y: 22 },
            { type: 'artillery', x: 16, y: 34 },
        ],
        enemyBuildings: [
            { type: 'construction_yard', x: 58, y: 24 },
            { type: 'power_plant', x: 62, y: 24 },
            { type: 'advanced_power', x: 62, y: 27 },
            { type: 'advanced_power', x: 62, y: 30 },
            { type: 'ore_refinery', x: 58, y: 28 },
            { type: 'ore_refinery', x: 58, y: 31 },
            { type: 'barracks', x: 62, y: 33 },
            { type: 'war_factory', x: 58, y: 34 },
            { type: 'radar_dome', x: 62, y: 36 },
            { type: 'tech_center', x: 66, y: 24 },
            { type: 'service_depot', x: 66, y: 27 },
            // Defense ring outer
            { type: 'turret', x: 53, y: 24 },
            { type: 'turret', x: 53, y: 28 },
            { type: 'turret', x: 53, y: 32 },
            { type: 'turret', x: 53, y: 36 },
            { type: 'pillbox', x: 54, y: 26 },
            { type: 'pillbox', x: 54, y: 30 },
            { type: 'pillbox', x: 54, y: 34 },
            { type: 'aa_gun', x: 55, y: 25 },
            { type: 'aa_gun', x: 55, y: 31 },
            { type: 'aa_gun', x: 55, y: 35 },
            // Inner defense
            { type: 'turret', x: 57, y: 27 },
            { type: 'turret', x: 57, y: 33 },
            { type: 'pillbox', x: 60, y: 27 },
            { type: 'pillbox', x: 60, y: 33 },
        ],
        enemyUnits: [
            { type: 'mammoth_tank', x: 56, y: 35 },
            { type: 'mammoth_tank', x: 57, y: 35 },
            { type: 'heavy_tank', x: 56, y: 37 },
            { type: 'heavy_tank', x: 57, y: 37 },
            { type: 'artillery', x: 55, y: 22 },
            { type: 'artillery', x: 56, y: 22 },
            { type: 'helicopter', x: 60, y: 22 },
            { type: 'harvester', x: 61, y: 28 },
            { type: 'harvester', x: 61, y: 31 },
            { type: 'infantry', x: 60, y: 36 },
            { type: 'rocket_soldier', x: 61, y: 36 },
        ],
        playerCredits: 12000,
        enemyCredits: 15000,
        terrain: [
            { type: 'circle', cx: 20, cy: 15, r: 4, tile: T.ORE },
            { type: 'circle', cx: 50, cy: 15, r: 4, tile: T.ORE },
            { type: 'circle', cx: 35, cy: 27, r: 6, tile: T.ORE },
            { type: 'circle', cx: 20, cy: 42, r: 4, tile: T.ORE },
            { type: 'circle', cx: 50, cy: 42, r: 4, tile: T.ORE },
            { type: 'scatter', count: 50, tile: T.ORE },
            { type: 'scatter', count: 60, tile: T.FOREST },
            { type: 'scatter', count: 35, tile: T.ROCK },
            { type: 'scatter', count: 10, tile: T.WATER },
        ],
        availableTech: ['power_plant', 'advanced_power', 'ore_refinery', 'barracks', 'war_factory', 'radar_dome', 'tech_center', 'turret', 'pillbox', 'aa_gun', 'service_depot'],
        availableUnits: ['infantry', 'rocket_soldier', 'grenadier', 'engineer', 'spy', 'light_tank', 'heavy_tank', 'artillery', 'harvester', 'apc', 'helicopter', 'mammoth_tank'],
        aiDifficulty: 0.95,
        victoryCondition: 'destroy_all',
        timeLimit: 0,
        seed: 2020,
    },
];
